# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"
  config.vm.network :forwarded_port, guest: 80, host: 8000

  config.ssh.forward_x11 = false

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.name = "gf-icfp-2018-VM"
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, privileged: false, :path => "setup-gf-icfp-2018.sh"
  config.vm.provision :shell, privileged: false, :path => "setup-vim.sh"
  config.vm.provision :shell, privileged: false, :path => "setup-emacs.sh"
  config.vm.provision :shell, privileged: false, :path => "setup-git.sh"
  config.vm.provision :shell, privileged: false, :path => "setup-tex.sh"
  config.vm.provision :shell, privileged: false, :path => "setup-sublime.sh"

  # disable the synced folder feature (Windows bug if commented out)
  config.vm.synced_folder ".", "/vagrant", disabled: true

end

